name: curl install workflow

on: push

jobs:
    installCurl:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              run: actions/checkout@v5
            
            - name: Execute shell script
              run: ./shell-demo.sh
               
            