name: curl install workflow

on: push

jobs:
    installCurl:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v5
            
            - name: Execute shell script
              run: |
                chmod +x .github/workflows/shell-demo.sh
                .github/workflows/shell-demo.sh

            