name: test the flow
# trigger
on: push
jobs: 
    firstJob:
        runs-on: ubuntu-latest
        steps: 
        
            - name: checkout action
              uses: actions/checkout@v4
              
            - name: welcome message
              run: echo "Welcome ubuntu"

      
              

            - name: List files
              run: ls

            - name: Read file
              run: cat README.md


